### ISSUE TITLE
Menu Items List

### ISSUE THREAD

**Issue by Xyntak** [benbaptist/benbot#49] opened 2016-02-20 18:49 UTC
Unable to delete the menu entries, edit them, or add new ones.

**Comment by benbaptist** [comment] 2016-03-08 20:47
I do need more clarification on this - because I haven't really ever been able to reproduce this bug.

**Comment by benbaptist** [comment] 2016-03-28 05:21
As you have not clarified anything on this in over two monhs, I will close this issue. Feel free to re-open it if you are still encountering this.

**Closed as completed by benbaptist** 2016-03-28 05:21 UTC
Labels: bug, invalid
